export const ANIME_LIST_REQUEST = "ANIME_LIST_REQUEST";
export const ANIME_LIST_SUCCESS = "ANIME_LIST_SUCCESS";
export const ANIME_LIST_FAIL = "ANIME_LIST_FAIL";

export const ANIME_DETAILS_REQUEST = "ANIME_DETAILS_REQUEST";
export const ANIME_DETAILS_SUCCESS = "ANIME_DETAILS_SUCCESS";
export const ANIME_DETAILS_FAIL = "ANIME_DETAILS_FAIL";
